# Generated by Django 3.1.3 on 2023-12-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0007_auto_20231213_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_id', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(choices=[('gpt-4-vision-preview', 'GPT 4 Vision'), ('gpt-4-1106-preview', 'GPT 4 Nov preview'), ('gpt-4-32k', 'GPT 4 32K model'), ('gpt-3.5-turbo-1106', 'GPT 3.5 Nov preview'), ('gpt-3.5-turbo-16k', 'GPT 3.5 16K model'), ('gpt-3.5-turbo', 'GPT 3 turbo model'), ('tts-1', 'Normal'), ('tts-1-hd', 'Normal'), ('whisper', 'Normal')], default='gpt-4-1106-preview', max_length=32)),
                ('memory_size', models.IntegerField(default=3)),
                ('max_token', models.IntegerField(default=500)),
                ('timeout', models.IntegerField(default=600)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system', 'Default prompt'), ('user', 'User message'), ('assistant', 'Model message')], default='user', max_length=9)),
                ('image', models.ImageField(null=True, upload_to='message_pic')),
                ('file', models.FileField(null=True, upload_to='message_file')),
                ('text', models.CharField(max_length=2048, null=True)),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gptutils.conversation')),
            ],
        ),
    ]
