# Generated by Django 3.1.3 on 2024-02-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptutils', '0002_auto_20231213_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='frequency_penalty',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=2, max_length=3),
        ),
        migrations.AddField(
            model_name='conversation',
            name='presence_penalty',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=2, max_length=3),
        ),
        migrations.AddField(
            model_name='conversation',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=2, max_length=3),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='model',
            field=models.CharField(choices=[('gpt-4-vision-preview', 'GPT 4 Vision with auto resolution'), ('gpt-4-vision-preview:high', 'GPT 4 Vision with high resolution'), ('gpt-4-vision-preview:low', 'GPT 4 Vision with low resolution'), ('gpt-4-1106-preview', 'GPT 4 Nov preview'), ('gpt-4-32k', 'GPT 4 32K model'), ('gpt-3.5-turbo-1106', 'GPT 3.5 Nov preview'), ('gpt-3.5-turbo-16k', 'GPT 3.5 16K model'), ('gpt-3.5-turbo', 'GPT 3 turbo model'), ('tts-1', 'Normal'), ('tts-1-hd', 'Normal'), ('whisper', 'Normal')], default='gpt-4-1106-preview', max_length=32),
        ),
    ]
