# Generated by Django 4.2.10 on 2024-02-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptutils', '0006_alter_conversation_id_alter_message_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='param',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='model',
            field=models.CharField(choices=[('gpt-4-vision-preview', 'GPT 4 Vision with auto resolution'), ('gpt-4-vision-preview:high', 'GPT 4 Vision with high resolution'), ('gpt-4-vision-preview:low', 'GPT 4 Vision with low resolution'), ('gpt-4-1106-preview', 'GPT 4 Nov preview'), ('gpt-4-32k', 'GPT 4 32K model'), ('gpt-3.5-turbo-1106', 'GPT 3.5 Nov preview'), ('gpt-3.5-turbo-16k', 'GPT 3.5 16K model'), ('gpt-3.5-turbo', 'GPT 3 turbo model'), ('plain-chat', 'Plain chat room for testing')], default='gpt-4-1106-preview', max_length=32),
        ),
    ]
