# Generated by Django 4.2.10 on 2024-02-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gptutils', '0008_message_file_id_alter_conversation_param_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='max_token',
            new_name='max_tokens',
        ),
    ]
