# Generated by Django 4.2.10 on 2024-02-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptutils', '0010_alter_conversation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='model',
            field=models.CharField(choices=[('gpt-4-vision-preview', 'GPT 4 Vision with auto resolution 128K (2023 Nov)'), ('gpt-4-vision-preview:high', 'GPT 4 Vision with high resolution 128K (2023 Nov)'), ('gpt-4-vision-preview:low', 'GPT 4 Vision with low resolution 128K (2023 Nov)'), ('gpt-4-0125-preview', 'GPT 4 latest preview 128K (2024 Jan)'), ('gpt-4-1106-preview', 'GPT 4 preview 128K (2023 Nov)'), ('gpt-4-0613', 'GPT 4 classic 8K (2023 Jun)'), ('gpt-3.5-turbo-0125', 'GPT 3.5 latest preview 16K (2024 Jan)'), ('gpt-3.5-turbo-1106', 'GPT 3.5 preview 16K (2023 Nov)'), ('gpt-3.5-turbo-0613', 'GPT 3.5 classic 4K (2023 Jun) depreciated'), ('gpt-3.5-turbo-16k', 'GPT 3.5 16K model (2023 Jun) depreciated'), ('plain-chat', 'Plain chat room for testing')], default='gpt-4-1106-preview', max_length=32),
        ),
    ]
