# Generated by Django 4.2.10 on 2024-02-23 04:15

from django.db import migrations, models
import gptutils.models


class Migration(migrations.Migration):

    dependencies = [
        ('gptutils', '0011_alter_conversation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=gptutils.models.message_file_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gptutils.models.message_image_path),
        ),
    ]
