# Generated by Django 4.2.10 on 2024-02-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptutils', '0014_alter_message_file_alter_message_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
