# Generated by Django 4.2.10 on 2024-06-04 15:04

from django.db import migrations, models
import django.db.models.deletion
import memcsv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creators", "0021_remove_creator_user_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemCSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(upload_to=memcsv.models.MemCSV_file_path),
                ),
                ("sharing_id", models.CharField(max_length=36, unique=True)),
                ("title", models.CharField(max_length=100, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "creator_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creators.creator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sharing_id", models.CharField(max_length=36, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "mem_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="memcsv.memcsv"
                    ),
                ),
            ],
        ),
    ]
