# Generated by Django 4.2.10 on 2024-06-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memcsv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Japanese_Key', models.CharField(max_length=50)),
                ('English_Value', models.CharField(max_length=50)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='memcsv.memcsv')),
            ],
        ),
    ]
