# Generated by Django 4.2.10 on 2024-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memcsv', '0002_worddict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memcsv',
            name='sharing_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
