# Generated by Django 4.2.10 on 2024-02-25 23:56

from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0020_alter_creator_image_alter_creator_motto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_id', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(default='Untitled Ep', max_length=100)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator')),
            ],
        ),
        migrations.CreateModel(
            name='NoteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('N', 'Normal Text'), ('U', 'URL'), ('T', 'Title'), ('S', 'Sub-title'), ('E', 'Example'), ('P', 'Proof'), ('C', 'Code'), ('Q', 'Quote'), ('I', 'Images'), ('F', 'Files'), ('L', 'List'), ('H', 'HTML')], default='N', max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to=notes.models.note_file_path)),
                ('file', models.FileField(blank=True, null=True, upload_to=notes.models.note_file_path)),
                ('is_AI_generated', models.BooleanField()),
                ('text', models.TextField(blank=True, null=True)),
                ('args', models.CharField(max_length=256, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator')),
                ('note_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator')),
                ('noteblock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.noteblock')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True)),
                ('is_AI_generated', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('noteblock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.noteblock')),
            ],
        ),
        migrations.CreateModel(
            name='NoteIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
                ('noteblock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.noteblock')),
            ],
        ),
    ]
