# Generated by Django 3.1.3 on 2024-02-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0009_auto_20240207_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_id', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True)),
                ('is_AI_generated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('N', 'Normal Text'), ('U', 'URL'), ('T', 'Title'), ('S', 'Sub title'), ('C', 'Code'), ('Q', 'Quote'), ('P', 'Picture'), ('L', 'List'), ('H', 'HTML')], default='N', max_length=1)),
                ('is_AI_generated', models.BooleanField()),
                ('content', models.CharField(max_length=2048, unique=True)),
                ('args', models.CharField(max_length=256, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
                ('tags', models.ManyToManyField(to='notes.Tag')),
            ],
        ),
    ]
