# Generated by Django 4.2.10 on 2024-03-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_noteblock_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteblock',
            name='args',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
