# Generated by Django 4.2.10 on 2024-03-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_noteblock_args"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noteblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("N", "Normal Text"),
                    ("U", "URL"),
                    ("T", "Title"),
                    ("S", "Sub-title"),
                    ("E", "Example"),
                    ("P", "Proof"),
                    ("C", "Code"),
                    ("Q", "Quote"),
                    ("I", "Images"),
                    ("L", "List"),
                    ("H", "HTML"),
                ],
                default="N",
                max_length=1,
            ),
        ),
    ]
