# Generated by Django 3.1.3 on 2023-12-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('expire_date', models.DateTimeField(null=True)),
                ('max_use', models.IntegerField(default=1)),
            ],
        ),
    ]
