# Generated by Django 3.1.3 on 2024-02-10 22:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0011_auto_20240207_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default='4SOCFl', max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 22, 57, 22, 368004, tzinfo=utc)),
        ),
    ]
