# Generated by Django 3.1.3 on 2024-02-10 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0013_auto_20240210_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default='BAEXeG', max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 23, 5, 56, 814560, tzinfo=utc)),
        ),
    ]
