# Generated by Django 4.2.10 on 2024-02-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0016_alter_creator_id_alter_verificationcode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(default='profile_pic/person-circle.svg', upload_to='profile_pic'),
        ),
    ]
