# Generated by Django 4.2.10 on 2024-02-23 03:54

import creators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0017_alter_creator_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(default='profile_pic/person-circle.svg', upload_to=creators.models.user_profile_path),
        ),
    ]
