# Generated by Django 4.2.10 on 2024-02-25 23:22

import creators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0019_alter_creator_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(blank=True, upload_to=creators.models.user_profile_path),
        ),
        migrations.AlterField(
            model_name='creator',
            name='motto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='social_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
