# Generated by Codex on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0021_remove_creator_user_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="editor_mode",
            field=models.CharField(
                choices=[("G", "GFM"), ("B", "Blocks"), ("P", "Plain Text")],
                default="P",
                max_length=1,
            ),
        ),
    ]
