# Generated by Django 4.2.10 on 2026-04-08 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("creators", "0025_invitationcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("github", "GitHub")],
                        max_length=16,
                    ),
                ),
                (
                    "provider_uid",
                    models.CharField(
                        help_text="Unique ID from the OAuth provider (e.g. Google sub, GitHub id).",
                        max_length=255,
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "provider_uid")},
            },
        ),
    ]
