# Generated by Django 4.2.10 on 2026-05-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0031_drop_invitation_verification_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, help_text='Cryptographically random URL-safe token returned to the SPA in the exchange response; must be supplied verbatim to the bind/create completion endpoints.', max_length=64, unique=True)),
                ('sub', models.CharField(db_index=True, help_text='Casdoor user sub claim from the verified JWT — what we stamp onto Creator.casdoor_sub once the link completes.', max_length=255)),
                ('casdoor_username', models.CharField(blank=True, default='', max_length=150)),
                ('casdoor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('casdoor_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('casdoor_groups', models.JSONField(blank=True, default=list)),
                ('access_token', models.TextField(help_text='Verified Casdoor JWT replayed back to the SPA in auth_payload after the link completes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='UTC; the bind/create endpoints reject the row past this.')),
            ],
            options={
                'indexes': [models.Index(fields=['sub', 'expires_at'], name='creators_li_sub_cf135a_idx')],
            },
        ),
    ]
