# Generated by Django 4.2.10 on 2026-05-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0032_link_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='Remote avatar URL refreshed from the Casdoor `avatar` claim. When set, the SPA prefers this over the locally-uploaded `image` so a single Casdoor profile change propagates to every Notechondria surface on next login. Empty = use the local `image`.', max_length=512),
        ),
        migrations.AddField(
            model_name='creator',
            name='casdoor_profile_synced_at',
            field=models.DateTimeField(blank=True, help_text="UTC timestamp of the most recent Casdoor profile refresh (`display_name`, `avatar_url`, `User.first_name` / `last_name` / `email`). Used by the in-process throttle in `_sync_creator_from_claims` so a busy SPA doesn't stamp the row on every JWT-authenticated request.", null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='User-facing display name. Refreshed from the Casdoor `displayName` claim on every authenticated request. Empty = fall back to `User.first_name + last_name` and ultimately to `User.username`. Editable from settings; the next Casdoor sign-in re-overwrites local edits with whatever the IdP currently has.', max_length=255),
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
