# Generated by Django 3.1.3 on 2024-02-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptutils', '0003_auto_20240207_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='model',
            field=models.CharField(choices=[('gpt-4-vision-preview', 'GPT 4 Vision with auto resolution'), ('gpt-4-vision-preview:high', 'GPT 4 Vision with high resolution'), ('gpt-4-vision-preview:low', 'GPT 4 Vision with low resolution'), ('gpt-4-1106-preview', 'GPT 4 Nov preview'), ('gpt-4-32k', 'GPT 4 32K model'), ('gpt-3.5-turbo-1106', 'GPT 3.5 Nov preview'), ('gpt-3.5-turbo-16k', 'GPT 3.5 16K model'), ('gpt-3.5-turbo', 'GPT 3 turbo model')], default='gpt-4-1106-preview', max_length=32),
        ),
    ]
