# Generated by Django 3.1.3 on 2023-12-05 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(max_length=100, null=True)),
                ('reputation', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('social_link', models.URLField(max_length=255, null=True)),
                ('credit_remains', models.IntegerField(default=0)),
                ('user_group', models.CharField(choices=[('A', 'Admin'), ('M', 'Manager'), ('N', 'Normal')], default='N', max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
