# Generated by Django 3.1.3 on 2023-12-13 21:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0006_auto_20231208_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default='bqQ85l', max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 22, 4, 3, 674055, tzinfo=utc)),
        ),
    ]
