# Generated by Codex on 2026-03-20

import notes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0021_remove_creator_user_group"),
        ("notes", "0004_alter_noteblock_block_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to=notes.models.course_cover_path)),
                ("is_default", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_edit", models.DateTimeField(auto_now=True)),
                (
                    "creator_id",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="creators.creator"),
                ),
            ],
            options={"ordering": ["title"]},
        ),
        migrations.CreateModel(
            name="CourseMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to=notes.models.course_media_path)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "course_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media_items", to="notes.course"),
                ),
            ],
            options={"ordering": ["date_created", "id"]},
        ),
        migrations.AddField(
            model_name="note",
            name="course_id",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notes", to="notes.course"),
        ),
    ]
