# Generated by Codex on 2026-03-21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0021_remove_creator_user_group"),
        ("notes", "0005_course_coursemedia_note_course_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannerEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("event_date", models.DateField(default=django.utils.timezone.localdate)),
                ("difficulty_weight", models.PositiveIntegerField(default=1)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_edit", models.DateTimeField(auto_now=True)),
                ("course_id", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="planner_events", to="notes.course")),
                ("creator_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="planner_events", to="creators.creator")),
            ],
            options={"ordering": ["event_date", "title", "id"]},
        ),
        migrations.CreateModel(
            name="HeatmapActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity_type", models.CharField(choices=[("C", "Created"), ("E", "Edited")], default="E", max_length=1)),
                ("activity_date", models.DateField(default=django.utils.timezone.localdate)),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("course_id", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="heatmap_activities", to="notes.course")),
                ("creator_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="heatmap_activities", to="creators.creator")),
                ("note_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="heatmap_activities", to="notes.note")),
            ],
            options={"ordering": ["activity_date", "id"]},
        ),
    ]
