# Generated by Codex on 2026-03-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0022_creator_editor_mode"),
        ("notes", "0006_plannerevent_heatmapactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="note",
            name="editor_mode",
            field=models.CharField(
                choices=[("G", "GFM"), ("B", "Blocks"), ("P", "Plain Text")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="metadata_json",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="CalendarFeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("source_kind", models.CharField(choices=[("I", "Imported iCal"), ("S", "Subscribed iCal")], default="I", max_length=1)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("raw_ical", models.TextField(blank=True, default="")),
                ("is_enabled", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_edit", models.DateTimeField(auto_now=True)),
                ("course_id", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="calendar_feeds", to="notes.course")),
                ("creator_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_feeds", to="creators.creator")),
            ],
            options={"ordering": ["title", "id"]},
        ),
        migrations.CreateModel(
            name="NoteVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=600, null=True)),
                ("content", models.TextField(blank=True, default="")),
                ("metadata_json", models.TextField(blank=True, default="")),
                ("editor_mode", models.CharField(default="P", max_length=1)),
                ("reason", models.CharField(default="manual", max_length=32)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("creator_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="note_versions", to="creators.creator")),
                ("note_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="notes.note")),
            ],
            options={"ordering": ["-date_created", "-id"]},
        ),
    ]
