# Generated by Django 4.2.10 on 2026-04-07 14:25

import uuid

from django.db import migrations, models
import django.db.models.deletion


def populate_uuid(apps, schema_editor):
    """Assign a unique UUID to every existing Note row."""
    Note = apps.get_model("notes", "Note")
    for note in Note.objects.all():
        note.uuid = uuid.uuid4()
        note.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0012_course_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="note_type",
            field=models.CharField(
                choices=[("N", "Normal"), ("C", "Comment")], default="N", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="source_note",
            field=models.ForeignKey(
                blank=True,
                help_text="For comment notes, the note being commented on.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="notes.note",
            ),
        ),
        # Step 1: Add uuid column nullable (no unique constraint yet)
        migrations.AddField(
            model_name="note",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        # Step 2: Backfill unique UUIDs for existing rows
        migrations.RunPython(populate_uuid, migrations.RunPython.noop),
        # Step 3: Make non-nullable and enforce unique constraint
        migrations.AlterField(
            model_name="note",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
