# Generated by Django 3.1.3 on 2023-12-07 03:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_auto_20231206_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default='DdXuqR', max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 3, 22, 26, 893185, tzinfo=utc)),
        ),
    ]
