# Generated by Django 3.1.3 on 2023-12-09 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_auto_20231206_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default='wqhmIr', max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 5, 0, 35, 726798, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='function',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
