# Generated by Django 3.1.3 on 2024-02-07 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0010_auto_20240207_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default='xi60fW', max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 22, 18, 15, 585729, tzinfo=utc)),
        ),
    ]
