# Generated by Django 3.1.3 on 2024-02-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0014_auto_20240210_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
