# Generated by Django 4.2.10 on 2024-02-25 23:05

import creators.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0018_alter_creator_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='image',
            field=models.ImageField(upload_to=creators.models.user_profile_path),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
