# Generated by Django 4.2.10 on 2024-03-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0020_alter_creator_image_alter_creator_motto_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="creator", name="user_group",),
    ]
