#!/usr/bin/env bash
set -euo pipefail

OUTPUT_PATH=${1:-.env.deploy}
SOURCE_PATH=${2:-}

mkdir -p "$(dirname "$OUTPUT_PATH")"

if [[ -n "$SOURCE_PATH" && -f "$SOURCE_PATH" ]]; then
  cp "$SOURCE_PATH" "$OUTPUT_PATH"
else
  : "${DJANGO_SECRET_KEY:?DJANGO_SECRET_KEY is required when no source env file is provided}"
  : "${POSTGRE_USERNAME:?POSTGRE_USERNAME is required when no source env file is provided}"
  : "${POSTGRE_PASSWORD:?POSTGRE_PASSWORD is required when no source env file is provided}"
  : "${POSTGRE_HOST:?POSTGRE_HOST is required when no source env file is provided}"
  : "${POSTGRE_PORT:?POSTGRE_PORT is required when no source env file is provided}"
  : "${POSTGRE_DB:?POSTGRE_DB is required when no source env file is provided}"

  cat > "$OUTPUT_PATH" <<EOF
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
DJANGO_DEBUG=${DJANGO_DEBUG:-False}
DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1}
DJANGO_ALLOWED_HOSTS_COMPOSE=${DJANGO_ALLOWED_HOSTS_COMPOSE:-localhost 127.0.0.1}
DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS:-http://localhost:9080,http://localhost:9060,http://localhost:8080}
DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL:-INFO}
DJANGO_LOG_FILE_NAME=${DJANGO_LOG_FILE_NAME:-notechondria}
DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-change-me}
APP_HOST_PORT=${APP_HOST_PORT:-9080}
BACKEND_HOST_PORT=${BACKEND_HOST_PORT:-9090}
FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT:-9060}
FRONTEND_FLUTTER_HOST_PORT=${FRONTEND_FLUTTER_HOST_PORT:-8080}
DB_HOST_PORT=${DB_HOST_PORT:-9032}
POSTGRE_USERNAME=${POSTGRE_USERNAME}
POSTGRE_PASSWORD=${POSTGRE_PASSWORD}
POSTGRE_HOST=${POSTGRE_HOST}
POSTGRE_PORT=${POSTGRE_PORT}
POSTGRE_DB=${POSTGRE_DB}
PRODUCTION_STATIC_ROOT=${PRODUCTION_STATIC_ROOT:-/home/staticfiles/}
PRODUCTION_MEDIA_ROOT=${PRODUCTION_MEDIA_ROOT:-/home/mediafiles/}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
SMTP_HOST=${SMTP_HOST:-}
SMTP_PORT=${SMTP_PORT:-587}
SMTP_USERNAME=${SMTP_USERNAME:-}
SMTP_PASSWORD=${SMTP_PASSWORD:-}
SMTP_USE_TLS=${SMTP_USE_TLS:-True}
SMTP_USE_SSL=${SMTP_USE_SSL:-False}
SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL:-no-reply@example.com}
EMAIL_VERIFICATION_TTL_HOURS=${EMAIL_VERIFICATION_TTL_HOURS:-24}
FRONTEND_VERIFY_URL=${FRONTEND_VERIFY_URL:-http://localhost:9060/#/verify}
FRONTEND_API_BASE_URL=${FRONTEND_API_BASE_URL:-/api/v1}
FRONTEND_BACKEND_ORIGIN=${FRONTEND_BACKEND_ORIGIN:-http://host.docker.internal:9080}
GITHUB_APP_ID=${GITHUB_APP_ID:-}
GITHUB_APP_CLIENT_ID=${GITHUB_APP_CLIENT_ID:-}
GITHUB_APP_CLIENT_SECRET=${GITHUB_APP_CLIENT_SECRET:-}
GITHUB_APP_PRIVATE_KEY_PATH=${GITHUB_APP_PRIVATE_KEY_PATH:-}
GITHUB_APP_WEBHOOK_SECRET=${GITHUB_APP_WEBHOOK_SECRET:-}
APP_IMAGE=${APP_IMAGE:-trancezero/notechondria:build-${BUILD_NUMBER:-local}}
NGINX_IMAGE=${NGINX_IMAGE:-trancezero/nginx:build-${BUILD_NUMBER:-local}}
FRONTEND_IMAGE=${FRONTEND_IMAGE:-trancezero/notechondria-frontend:build-${BUILD_NUMBER:-local}}
DB_AUTO_REINIT_IF_MISMATCH=${DB_AUTO_REINIT_IF_MISMATCH:-False}
EOF
fi

chmod 600 "$OUTPUT_PATH"
echo "Deployment env prepared at $OUTPUT_PATH"
