from django.urls import path

from creators.api import (
    LoginApiView,
    LogoutApiView,
    PasswordResetConfirmApiView,
    PasswordResetRequestApiView,
    RegisterApiView,
    ResendVerificationApiView,
    SettingsApiView,
    SessionApiView,
    VerifyEmailApiView,
)
from notes.api import (
    ActivityApiView,
    ActivityWeekApiView,
    CalendarFeedDetailApiView,
    CalendarFeedListCreateApiView,
    CourseDetailApiView,
    CourseListApiView,
    CourseNotesApiView,
    FrontPageApiView,
    HeatmapApiView,
    NoteBlocksApiView,
    NoteDetailApiView,
    NoteHistoryApiView,
    NoteListCreateApiView,
    NoteRestoreApiView,
    NoteSessionDetailApiView,
    NoteSessionListCreateApiView,
    NoteSnapshotApiView,
    PlannerEventDetailApiView,
    PlannerEventListCreateApiView,
    ReorderBlocksApiView,
    SingleBlockApiView,
)


urlpatterns = [
    path("health/", FrontPageApiView.health, name="health"),
    path("auth/register/", RegisterApiView.as_view(), name="register"),
    path("auth/verify-email/", VerifyEmailApiView.as_view(), name="verify-email"),
    path("auth/resend-verification/", ResendVerificationApiView.as_view(), name="resend-verification"),
    path("auth/login/", LoginApiView.as_view(), name="login"),
    path("auth/password-reset/", PasswordResetRequestApiView.as_view(), name="password-reset"),
    path("auth/password-reset/confirm/", PasswordResetConfirmApiView.as_view(), name="password-reset-confirm"),
    path("auth/logout/", LogoutApiView.as_view(), name="logout"),
    path("auth/session/", SessionApiView.as_view(), name="session"),
    path("front-page/", FrontPageApiView.as_view(), name="front-page"),
    path("courses/", CourseListApiView.as_view(), name="course-list"),
    path("courses/<int:course_id>/", CourseDetailApiView.as_view(), name="course-detail"),
    path("courses/<int:course_id>/notes/", CourseNotesApiView.as_view(), name="course-notes"),
    path("notes/", NoteListCreateApiView.as_view(), name="note-list-create"),
    path("notes/<int:note_id>/", NoteDetailApiView.as_view(), name="note-detail"),
    path("notes/<int:note_id>/history/", NoteHistoryApiView.as_view(), name="note-history"),
    path("notes/<int:note_id>/snapshot/", NoteSnapshotApiView.as_view(), name="note-snapshot"),
    path("notes/<int:note_id>/restore/<int:version_id>/", NoteRestoreApiView.as_view(), name="note-restore"),
    path("note-sessions/", NoteSessionListCreateApiView.as_view(), name="note-session-list-create"),
    path("note-sessions/<int:session_id>/", NoteSessionDetailApiView.as_view(), name="note-session-detail"),
    path("notes/<int:note_id>/blocks/", NoteBlocksApiView.as_view(), name="note-blocks"),
    path("notes/<int:note_id>/reorder/", ReorderBlocksApiView.as_view(), name="note-reorder"),
    path("blocks/<int:block_id>/", SingleBlockApiView.as_view(), name="block-detail"),
    path("activity/", ActivityApiView.as_view(), name="activity"),
    path("activity/week/", ActivityWeekApiView.as_view(), name="activity-week"),
    path("heatmap/", HeatmapApiView.as_view(), name="heatmap"),
    path("calendar-feeds/", CalendarFeedListCreateApiView.as_view(), name="calendar-feeds"),
    path("calendar-feeds/<int:feed_id>/", CalendarFeedDetailApiView.as_view(), name="calendar-feed-detail"),
    path("planner-events/", PlannerEventListCreateApiView.as_view(), name="planner-events"),
    path("planner-events/<int:event_id>/", PlannerEventDetailApiView.as_view(), name="planner-event-detail"),
    path("settings/", SettingsApiView.as_view(), name="settings"),
]
