from django.urls import path

from notechondria.api_views import handshake as handshake_view

from creators.api import (
    BindGithubApiView,
    BindGoogleApiView,
    ChangeEmailApiView,
    ChangePasswordApiView,
    GitHubOAuthApiView,
    GoogleOAuthApiView,
    LoginApiView,
    LogoutApiView,
    OAuthConfigApiView,
    PasswordResetConfirmApiView,
    PasswordResetRequestApiView,
    RegisterApiView,
    ResendVerificationApiView,
    RotateApiKeyApiView,
    SendIdentityCodeApiView,
    SettingsApiView,
    SessionApiView,
    SocialAccountListApiView,
    SocialAccountUnlinkApiView,
    ValidateInvitationApiView,
    VerifyEmailApiView,
)
from notes.api import (
    ActivityApiView,
    ActivityWeekApiView,
    CalendarFeedDetailApiView,
    CalendarFeedListCreateApiView,
    CourseDetailApiView,
    CourseListApiView,
    CourseNotesApiView,
    CourseReorderApiView,
    CourseOpenApiView,
    CourseSubscribeApiView,
    DeletedNoteEmptyApiView,
    DeletedNoteListApiView,
    DeletedNoteRestoreApiView,
    FrontPageApiView,
    HeatmapApiView,
    NoteAttachmentApiView,
    NoteAttachmentDetailApiView,
    NoteBlocksApiView,
    NoteByUuidApiView,
    NoteDetailApiView,
    NoteHistoryApiView,
    NoteListCreateApiView,
    NoteRestoreApiView,
    NoteSessionDetailApiView,
    NoteSessionListCreateApiView,
    NoteSnapshotApiView,
    PlannerEventDetailApiView,
    PlannerEventListCreateApiView,
    ReorderBlocksApiView,
    SingleBlockApiView,
    TemplateCourseRestoreApiView,
)


urlpatterns = [
    path("health/", FrontPageApiView.health, name="health"),
    path("handshake/", handshake_view, name="handshake"),
    path("auth/register/", RegisterApiView.as_view(), name="register"),
    path("auth/validate-invitation/", ValidateInvitationApiView.as_view(), name="validate-invitation"),
    path("auth/verify-email/", VerifyEmailApiView.as_view(), name="verify-email"),
    path("auth/resend-verification/", ResendVerificationApiView.as_view(), name="resend-verification"),
    path("auth/login/", LoginApiView.as_view(), name="login"),
    path("auth/password-reset/", PasswordResetRequestApiView.as_view(), name="password-reset"),
    path("auth/password-reset/confirm/", PasswordResetConfirmApiView.as_view(), name="password-reset-confirm"),
    path("auth/send-identity-code/", SendIdentityCodeApiView.as_view(), name="send-identity-code"),
    path("auth/rotate-api-key/", RotateApiKeyApiView.as_view(), name="rotate-api-key"),
    path("auth/change-password/", ChangePasswordApiView.as_view(), name="change-password"),
    path("auth/change-email/", ChangeEmailApiView.as_view(), name="change-email"),
    path("auth/logout/", LogoutApiView.as_view(), name="logout"),
    path("auth/session/", SessionApiView.as_view(), name="session"),
    path("auth/oauth-config/", OAuthConfigApiView.as_view(), name="oauth-config"),
    path("auth/google/", GoogleOAuthApiView.as_view(), name="google-oauth"),
    path("auth/github/", GitHubOAuthApiView.as_view(), name="github-oauth"),
    path("auth/social-accounts/", SocialAccountListApiView.as_view(), name="social-accounts"),
    path("auth/social-accounts/<str:provider>/", SocialAccountUnlinkApiView.as_view(), name="social-account-unlink"),
    path("auth/bind/google/", BindGoogleApiView.as_view(), name="bind-google"),
    path("auth/bind/github/", BindGithubApiView.as_view(), name="bind-github"),
    path("front-page/", FrontPageApiView.as_view(), name="front-page"),
    path("courses/", CourseListApiView.as_view(), name="course-list"),
    path("courses/reorder/", CourseReorderApiView.as_view(), name="course-reorder"),
    path("courses/<int:course_id>/", CourseDetailApiView.as_view(), name="course-detail"),
    path("courses/<int:course_id>/notes/", CourseNotesApiView.as_view(), name="course-notes"),
    path("courses/<int:course_id>/subscribe/", CourseSubscribeApiView.as_view(), name="course-subscribe"),
    path("courses/<int:course_id>/open/", CourseOpenApiView.as_view(), name="course-open"),
    path("admin/template-courses/restore/", TemplateCourseRestoreApiView.as_view(), name="template-course-restore"),
    path("notes/", NoteListCreateApiView.as_view(), name="note-list-create"),
    path("notes/deleted/", DeletedNoteListApiView.as_view(), name="deleted-note-list"),
    path("notes/deleted/empty/", DeletedNoteEmptyApiView.as_view(), name="deleted-note-empty"),
    path("notes/uuid/<uuid:note_uuid>/", NoteByUuidApiView.as_view(), name="note-by-uuid"),
    path("notes/<int:note_id>/", NoteDetailApiView.as_view(), name="note-detail"),
    path("notes/<int:note_id>/restore/", DeletedNoteRestoreApiView.as_view(), name="deleted-note-restore"),
    path("notes/<int:note_id>/history/", NoteHistoryApiView.as_view(), name="note-history"),
    path("notes/<int:note_id>/snapshot/", NoteSnapshotApiView.as_view(), name="note-snapshot"),
    path("notes/<int:note_id>/restore/<int:version_id>/", NoteRestoreApiView.as_view(), name="note-restore"),
    path("note-sessions/", NoteSessionListCreateApiView.as_view(), name="note-session-list-create"),
    path("note-sessions/<int:session_id>/", NoteSessionDetailApiView.as_view(), name="note-session-detail"),
    path("notes/<int:note_id>/attachments/", NoteAttachmentApiView.as_view(), name="note-attachments"),
    path("notes/<int:note_id>/attachments/<int:attachment_id>/", NoteAttachmentDetailApiView.as_view(), name="note-attachment-detail"),
    path("notes/<int:note_id>/blocks/", NoteBlocksApiView.as_view(), name="note-blocks"),
    path("notes/<int:note_id>/reorder/", ReorderBlocksApiView.as_view(), name="note-reorder"),
    path("blocks/<int:block_id>/", SingleBlockApiView.as_view(), name="block-detail"),
    path("activity/", ActivityApiView.as_view(), name="activity"),
    path("activity/week/", ActivityWeekApiView.as_view(), name="activity-week"),
    path("heatmap/", HeatmapApiView.as_view(), name="heatmap"),
    path("calendar-feeds/", CalendarFeedListCreateApiView.as_view(), name="calendar-feeds"),
    path("calendar-feeds/<int:feed_id>/", CalendarFeedDetailApiView.as_view(), name="calendar-feed-detail"),
    path("planner-events/", PlannerEventListCreateApiView.as_view(), name="planner-events"),
    path("planner-events/<int:event_id>/", PlannerEventDetailApiView.as_view(), name="planner-event-detail"),
    path("settings/", SettingsApiView.as_view(), name="settings"),
]
