"""
Django settings for notechondria project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE_DIR.parent

load_dotenv(REPO_ROOT / ".env")
load_dotenv(BASE_DIR / ".env", override=False)


def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = ""):
    raw = os.getenv(name, default)
    if not raw:
        return []
    normalized = raw.replace(",", " ")
    return [item.strip() for item in normalized.split() if item.strip()]


def env_path(name: str, default):
    raw = os.getenv(name)
    if not raw:
        return str(default)
    candidate = raw.strip()
    if os.name != "nt":
        if len(candidate) >= 2 and candidate[1] == ":":
            return str(default)
        if not candidate.startswith("/"):
            return str(default)
    return candidate

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', False)

_default_hosts = "localhost 127.0.0.1"
# Auto-detect Render deployment hostname (set automatically by Render)
_render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME", "")
if _render_host:
    _default_hosts += f" {_render_host}"
# Custom domain pointing to this backend (e.g. notechondria.trance-0.com)
_custom_domain = os.getenv("BACKEND_CUSTOM_DOMAIN", "")
if _custom_domain:
    _default_hosts += f" {_custom_domain}"

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", _default_hosts)
# Union: BACKEND_CUSTOM_DOMAIN and RENDER_EXTERNAL_HOSTNAME must be
# accepted even when DJANGO_ALLOWED_HOSTS is explicitly set. Previously
# an explicit DJANGO_ALLOWED_HOSTS silently superseded _default_hosts,
# so setting BACKEND_CUSTOM_DOMAIN in Northflank env had no effect —
# the backend returned 400 DisallowedHost for the user's own domain
# (`notechondria.trance-0.com` / `note.zheyuanwu.com`). The union runs
# after env_list so operators can still whitelist extra hosts
# centrally, but the platform-provided hostnames are always trusted.
for _auto_host in (_custom_domain, _render_host):
    if _auto_host and _auto_host not in ALLOWED_HOSTS and "*" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS = [*ALLOWED_HOSTS, _auto_host]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # apps created
    'gptutils',
    'courses',
    'planner',
    'notes',
    'creators',
    'mcp',
    'rest_framework',
    'rest_framework.authtoken',
    'storages',
]

MIDDLEWARE = [
    # RequestTimingMiddleware is first so it captures the full end-to-end
    # wall time, including everything downstream (auth, CORS, views, DB).
    'notechondria.middleware.RequestTimingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'notechondria.middleware.ApiCorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# add trusted CDN
_default_csrf = f"http://localhost:{os.getenv('APP_HOST_PORT', '9080')}"
if _render_host:
    _default_csrf += f",https://{_render_host}"
if _custom_domain:
    _default_csrf += f",https://{_custom_domain}"
# Frontend origin for CORS (e.g. https://username.github.io)
_frontend_origin = os.getenv("FRONTEND_ORIGIN", "")
if _frontend_origin:
    _default_csrf += f",{_frontend_origin}"
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", _default_csrf)
# Same rationale as the ALLOWED_HOSTS union above: an explicit
# DJANGO_CSRF_TRUSTED_ORIGINS shouldn't silently drop the
# platform-provided hostnames, or cross-origin POSTs from the
# frontend to the user's own domain 403 with a CSRF rejection.
for _auto_host in (_custom_domain, _render_host):
    if not _auto_host:
        continue
    _origin = f"https://{_auto_host}"
    if _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS = [*CSRF_TRUSTED_ORIGINS, _origin]
if _frontend_origin and _frontend_origin not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [*CSRF_TRUSTED_ORIGINS, _frontend_origin]

ROOT_URLCONF = 'notechondria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # this is the place to put global templates
        'DIRS': [os.path.join(BASE_DIR, 'notechondria','templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notechondria.views.is_offline'
            ],
            'libraries': {
                'svg_tags': 'notechondria.templatetags.svg_tags',
                'md_str_esc': 'notechondria.templatetags.md_str_esc',
            }
        },
    },
]

# Session settings
# https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-SESSION_COOKIE_AGE
# We set to at most 3 days
SESSION_COOKIE_AGE=259200

WSGI_APPLICATION = 'notechondria.wsgi.application'

# Logging
# https://docs.djangoproject.com/en/4.2/topics/logging/

LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        # print level in console
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # dedicated handler for RequestTimingMiddleware: minimal formatter,
        # DEBUG level so info/warning/critical all pass through.
        'console_access': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'access',
        },
        # print level in log file
        'file': {
            # de-comment the line below for detailed (super detailed) debug in django
            # 'level': 'DEBUG',
            'level': 'INFO',
            'class': 'logging.FileHandler',
            # if you need to store it outside of current project folder, remove the join base part.
            'filename': os.path.join(LOG_DIR, f"{os.getenv('DJANGO_LOG_FILE_NAME', 'logs')}-{datetime.now().strftime('%Y%m%d')}.log"),
            'formatter': 'verbose',
            'encoding':'utf8',
        },
    },
    'formatters': {
        'verbose': {
            'format': u'%(levelname)s [%(asctime)s] %(name)s.%(funcName)s:%(lineno)s- %(message)r',
        },
        # RequestTimingMiddleware emits already-colored messages; keep the
        # formatter minimal so we don't escape-mangle the ANSI sequences.
        'access': {
            'format': '%(asctime)s %(levelname)-8s %(message)s',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        # Django's default request handler emits a duplicate WARNING
        # ("Unauthorized: /path") on top of our own access log for
        # every 4xx. Silence it by raising the threshold to ERROR so
        # 4xx/5xx don't double-log and we keep our structured access
        # line as the single source of truth for request outcomes.
        # 5xx crashes still surface here because Django logs the full
        # traceback at ERROR level before our middleware runs its log.
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'notechondria.access': {
            'handlers': ['console_access'],
            'level': 'INFO',
            'propagate': False,
        },
        # Shaped auth/permission failure lines emitted by our DRF
        # exception handler. Goes to the standard `console` (verbose)
        # + `file` handlers so both operator streams pick it up.
        'notechondria.auth': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Note CRUD + sync structured events (create / update / delete /
        # attachment / version restore). All lines are §1.7-shaped
        # ("<consequence>: Backend.Notes.<area>/<process> \u2014 <cause>").
        'notechondria.notes': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    # all the logging will propagate to root. so use root to save your log
    'root': {
        'handlers': ['file', ],
        'level': 'DEBUG',
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_database_url = os.getenv('DATABASE_URL')
if _database_url:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(_database_url, conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRE_DB', 'postgres'),
            'USER': os.getenv('POSTGRE_USERNAME'),
            'PASSWORD': os.getenv('POSTGRE_PASSWORD'),
            'HOST': os.getenv('POSTGRE_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRE_PORT', '5432'),
        }
    }

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # MCP API keys (long-lived, per-creator, ``Authorization:
        # Bearer ntc_...``). Listed first so MCP traffic resolves
        # without ever consulting the Casdoor JWT path.
        "creators.authentication.ApiKeyAuthentication",
        # Casdoor JWTs are the only user-facing credential as of 0.1.106
        # (post invitation/verification/session cleanup). The class is
        # a no-op when CASDOOR_* env vars are unset; otherwise it
        # validates Bearer JWTs against the configured Casdoor app.
        # Bearer headers starting with `ntc_` are handed back to
        # ApiKeyAuthentication explicitly inside the class.
        # See docs/integrations/casdoor-migration.md.
        "creators.casdoor_auth.CasdoorJWTAuthentication",
        # DRF's stock TokenAuthentication is kept for the auth-token
        # rows in `authtoken_token` that still back a few internal
        # tooling paths (admin scripts, MCP rotate tests).
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    # Our handler emits one AGENTS.md §1.7-shaped log line per
    # auth/permission failure, then delegates to DRF's default
    # handler for the actual HTTP response.
    "EXCEPTION_HANDLER": "notechondria.drf_exception_handler.handle",
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  
        "OPTIONS": {
            "min_length": 9,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Automatic primary key for those who don't set, and the default feature name is id
# https://docs.djangoproject.com/en/3.2/topics/db/models/#automatic-primary-key-fields
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# you should not use django to process your static files, the static url should be set to other file providing url
STATIC_URL = '/static/'

# static file in the project folder (global)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# keep Django and nginx pointed at the same static directory regardless of DEBUG
STATIC_ROOT = env_path('DJANGO_PRODUCTION_STATIC_ROOT', BASE_DIR / 'productionfiles')

# Image files (jpg, jpeg)
# reference: https://djangocentral.com/uploading-images-with-django/

# Base url to serve media files
MEDIA_URL = '/media/'

# keep Django and nginx pointed at the same media directory regardless of DEBUG
MEDIA_ROOT = env_path('DJANGO_PRODUCTION_MEDIA_ROOT', BASE_DIR / 'mediafiles')

# ---------------------------------------------------------------------------
# Cloudflare R2 storage (S3-compatible)
# ---------------------------------------------------------------------------
# When CLOUDFLARE_R2_BUCKET_NAME is set, both static and media files are
# served from R2.  This is required on Render (no persistent disk) and
# optional for Docker Compose (persistent volumes + nginx work fine).
_R2_BUCKET = os.getenv('CLOUDFLARE_R2_BUCKET_NAME', '').strip()
_R2_ACCOUNT_ID = os.getenv('CLOUDFLARE_R2_ACCOUNT_ID', '').strip()
_R2_ACCESS_KEY = os.getenv('CLOUDFLARE_R2_ACCESS_KEY_ID', '').strip()
_R2_SECRET_KEY = os.getenv('CLOUDFLARE_R2_SECRET_ACCESS_KEY', '').strip()
_R2_CUSTOM_DOMAIN = os.getenv('CLOUDFLARE_R2_CUSTOM_DOMAIN', '').strip()

if _R2_BUCKET:
    # Validate that all required credentials are present.
    _missing = [
        name for name, val in [
            ('CLOUDFLARE_R2_ACCOUNT_ID', _R2_ACCOUNT_ID),
            ('CLOUDFLARE_R2_ACCESS_KEY_ID', _R2_ACCESS_KEY),
            ('CLOUDFLARE_R2_SECRET_ACCESS_KEY', _R2_SECRET_KEY),
        ] if not val
    ]
    if _missing:
        raise RuntimeError(
            f"Cloudflare R2 bucket is configured (CLOUDFLARE_R2_BUCKET_NAME={_R2_BUCKET!r}) "
            f"but the following required env vars are missing: {', '.join(_missing)}"
        )

    # S3-compatible endpoint for Cloudflare R2.
    _R2_ENDPOINT = f'https://{_R2_ACCOUNT_ID}.r2.cloudflarestorage.com'

    # Public URL base.  When a Cloudflare R2 custom domain (or r2.dev
    # subdomain) is set, use it.  Otherwise fall back to the S3 endpoint.
    _R2_URL_BASE = f'https://{_R2_CUSTOM_DOMAIN}' if _R2_CUSTOM_DOMAIN else _R2_ENDPOINT

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'bucket_name': _R2_BUCKET,
                'endpoint_url': _R2_ENDPOINT,
                'access_key': _R2_ACCESS_KEY,
                'secret_key': _R2_SECRET_KEY,
                'custom_domain': _R2_CUSTOM_DOMAIN or None,
                'default_acl': None,
                'location': 'media',
                'file_overwrite': False,
                'signature_version': 's3v4',
                'region_name': 'auto',
            },
        },
        'staticfiles': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'bucket_name': _R2_BUCKET,
                'endpoint_url': _R2_ENDPOINT,
                'access_key': _R2_ACCESS_KEY,
                'secret_key': _R2_SECRET_KEY,
                'custom_domain': _R2_CUSTOM_DOMAIN or None,
                'default_acl': None,
                'location': 'static',
                'file_overwrite': True,
                'signature_version': 's3v4',
                'region_name': 'auto',
            },
        },
    }
    STATIC_URL = f'{_R2_URL_BASE}/static/'
    MEDIA_URL = f'{_R2_URL_BASE}/media/'

# Maximum upload size: 20 MB (for note attachments).
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

# Offline development tag
OFFLINE = False

# login url

LOGIN_URL="/creators/login"

# LOGIN_REDIRECT_URL="/creators/profile"

# Experimental: GitHub App used for the per-user data-sync feature.
# Unrelated to authentication — Casdoor is the only third-party sign-in
# surface. The data-sync flow installs a GitHub App into the user's
# account so Notechondria can read and push to a single user-chosen
# repository.
GITHUB_DATA_SYNC_APP_NAME = os.getenv("GITHUB_DATA_SYNC_APP_NAME", "")
GITHUB_DATA_SYNC_APP_CLIENT_ID = os.getenv("GITHUB_DATA_SYNC_APP_CLIENT_ID", "")
GITHUB_DATA_SYNC_APP_CLIENT_SECRET = os.getenv("GITHUB_DATA_SYNC_APP_CLIENT_SECRET", "")
GITHUB_DATA_SYNC_APP_PRIVATE_KEY = os.getenv("GITHUB_DATA_SYNC_APP_PRIVATE_KEY", "")
GITHUB_DATA_SYNC_APP_INSTALL_URL = os.getenv("GITHUB_DATA_SYNC_APP_INSTALL_URL", "")

# Casdoor (https://casdoor.org). Phase 2 of the auth migration plan
# — see docs/integrations/casdoor-migration.md. When CASDOOR_ENDPOINT
# is empty, the JWT-validating authentication class is a no-op and
# the exchange endpoint returns 503; existing MultiSessionAuthentication
# + LoginApiView paths keep working unchanged. Set the values below
# to flip on shadow mode; cutover happens in a future round once the
# Flutter SDK leg lands.
CASDOOR_ENDPOINT = os.getenv("CASDOOR_ENDPOINT", "").rstrip("/")
CASDOOR_CLIENT_ID = os.getenv("CASDOOR_CLIENT_ID", "")
CASDOOR_CLIENT_SECRET = os.getenv("CASDOOR_CLIENT_SECRET", "")
CASDOOR_ORG_NAME = os.getenv("CASDOOR_ORG_NAME", "")
CASDOOR_APP_NAME = os.getenv("CASDOOR_APP_NAME", "")
# Single-line PEM with literal `\n` escapes — the JWT verifier
# normalizes it (same shape as GITHUB_DATA_SYNC_APP_PRIVATE_KEY).
CASDOOR_CERTIFICATE = os.getenv("CASDOOR_CERTIFICATE", "")
# How long to cache JWT-verification results (in seconds). The
# verifier itself is stateless; this just amortizes the JWKS cert
# parsing cost when the same token shows up again within the window.
CASDOOR_TOKEN_CACHE_TTL = int(os.getenv("CASDOOR_TOKEN_CACHE_TTL", "300"))

# JWT claim-name mapping (modeled on the Nextcloud user_oidc plugin's
# attribute mapping). Each value is a comma-separated list of claim
# names tried in order — the first non-empty value wins. Lets the
# operator point Notechondria at whatever Casdoor's Token Format tab
# is configured to emit (e.g. preferred_username vs name vs uid)
# without a code change. Defaults preserve the historical 0.1.96
# behavior.
CASDOOR_CLAIM_SUB = os.getenv("CASDOOR_CLAIM_SUB", "id,sub")
CASDOOR_CLAIM_USERNAME = os.getenv(
    "CASDOOR_CLAIM_USERNAME", "preferred_username,name"
)
CASDOOR_CLAIM_EMAIL = os.getenv("CASDOOR_CLAIM_EMAIL", "email")
CASDOOR_CLAIM_DISPLAY_NAME = os.getenv(
    "CASDOOR_CLAIM_DISPLAY_NAME", "displayName,name"
)
CASDOOR_CLAIM_GIVEN_NAME = os.getenv(
    "CASDOOR_CLAIM_GIVEN_NAME", "given_name,firstName"
)
CASDOOR_CLAIM_FAMILY_NAME = os.getenv(
    "CASDOOR_CLAIM_FAMILY_NAME", "family_name,lastName"
)
CASDOOR_CLAIM_GROUPS = os.getenv("CASDOOR_CLAIM_GROUPS", "groups")
# Avatar URL claim, refreshed onto Creator.avatar_url every login
# (see _sync_creator_from_claims in creators/casdoor_auth.py). Empty
# leaves the SPA falling back to the locally-uploaded Creator.image.
CASDOOR_CLAIM_AVATAR = os.getenv("CASDOOR_CLAIM_AVATAR", "avatar")
# Credential-hash claims (Casdoor application Token Format: JWT-Custom
# with the Password / Password salt / Password type token fields).
# Mirrored into User.password by creators/casdoor_password.py so the
# email/password fallback login accepts the user's current Casdoor
# password during Casdoor outages. Current Casdoor builds scrub the
# `password` claim value server-side, so the claims path stays dormant
# until the IdP emits it; the ROPC grant in LoginSerializer covers the
# gap at fallback-login time.
CASDOOR_CLAIM_PASSWORD = os.getenv("CASDOOR_CLAIM_PASSWORD", "password")
CASDOOR_CLAIM_PASSWORD_SALT = os.getenv(
    "CASDOOR_CLAIM_PASSWORD_SALT", "passwordSalt"
)
CASDOOR_CLAIM_PASSWORD_TYPE = os.getenv(
    "CASDOOR_CLAIM_PASSWORD_TYPE", "passwordType"
)

# Django's default hasher list plus the plain-bcrypt verifier, which
# is NOT in the defaults. Needed so a `bcrypt$<hash>` value mirrored
# verbatim from a Casdoor bcrypt credential (passwordType=bcrypt)
# verifies on the fallback login path. PBKDF2 stays first so
# set_password keeps producing the Django-default format.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.BCryptPasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Group-based ACL. Comma-separated list of group names that must
# include at least one of the user's `groups` claim values for the
# JWT to authenticate. Empty (default) = no gating; any successfully-
# verified Casdoor JWT is accepted. Group strings are compared
# case-sensitively against the JWT array exactly as Casdoor emits
# them (Casdoor typically sends `org/group_name` for group-scoped
# membership). Mirrors the user_oidc `Restrict login to a list of
# groups` toggle.
CASDOOR_REQUIRED_GROUPS = os.getenv("CASDOOR_REQUIRED_GROUPS", "")
