"""
Django settings for notechondria project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE_DIR.parent

load_dotenv(REPO_ROOT / ".env")
load_dotenv(BASE_DIR / ".env", override=False)


def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = ""):
    raw = os.getenv(name, default)
    if not raw:
        return []
    normalized = raw.replace(",", " ")
    return [item.strip() for item in normalized.split() if item.strip()]


def env_path(name: str, default):
    raw = os.getenv(name)
    if not raw:
        return str(default)
    candidate = raw.strip()
    if os.name != "nt":
        if len(candidate) >= 2 and candidate[1] == ":":
            return str(default)
        if not candidate.startswith("/"):
            return str(default)
    return candidate

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', False)

_default_hosts = "localhost 127.0.0.1"
# Auto-detect Render deployment hostname (set automatically by Render)
_render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME", "")
if _render_host:
    _default_hosts += f" {_render_host}"
# Custom domain pointing to this backend (e.g. notechondria.trance-0.com)
_custom_domain = os.getenv("BACKEND_CUSTOM_DOMAIN", "")
if _custom_domain:
    _default_hosts += f" {_custom_domain}"

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", _default_hosts)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # apps created
    'gptutils',
    'courses',
    'planner',
    'notes',
    'creators',
    'mcp',
    'rest_framework',
    'rest_framework.authtoken',
    'storages',
]

MIDDLEWARE = [
    # RequestTimingMiddleware is first so it captures the full end-to-end
    # wall time, including everything downstream (auth, CORS, views, DB).
    'notechondria.middleware.RequestTimingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'notechondria.middleware.ApiCorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# add trusted CDN
_default_csrf = f"http://localhost:{os.getenv('APP_HOST_PORT', '9080')}"
if _render_host:
    _default_csrf += f",https://{_render_host}"
if _custom_domain:
    _default_csrf += f",https://{_custom_domain}"
# Frontend origin for CORS (e.g. https://username.github.io)
_frontend_origin = os.getenv("FRONTEND_ORIGIN", "")
if _frontend_origin:
    _default_csrf += f",{_frontend_origin}"
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", _default_csrf)

ROOT_URLCONF = 'notechondria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # this is the place to put global templates
        'DIRS': [os.path.join(BASE_DIR, 'notechondria','templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notechondria.views.is_offline'
            ],
            'libraries': {
                'svg_tags': 'notechondria.templatetags.svg_tags',
                'md_str_esc': 'notechondria.templatetags.md_str_esc',
            }
        },
    },
]

# Session settings
# https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-SESSION_COOKIE_AGE
# We set to at most 3 days
SESSION_COOKIE_AGE=259200

WSGI_APPLICATION = 'notechondria.wsgi.application'

# Logging
# https://docs.djangoproject.com/en/4.2/topics/logging/

LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        # print level in console
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # dedicated handler for RequestTimingMiddleware: minimal formatter,
        # DEBUG level so info/warning/critical all pass through.
        'console_access': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'access',
        },
        # print level in log file
        'file': {
            # de-comment the line below for detailed (super detailed) debug in django
            # 'level': 'DEBUG',
            'level': 'INFO',
            'class': 'logging.FileHandler',
            # if you need to store it outside of current project folder, remove the join base part.
            'filename': os.path.join(LOG_DIR, f"{os.getenv('DJANGO_LOG_FILE_NAME', 'logs')}-{datetime.now().strftime('%Y%m%d')}.log"),
            'formatter': 'verbose',
            'encoding':'utf8',
        },
    },
    'formatters': {
        'verbose': {
            'format': u'%(levelname)s [%(asctime)s] %(name)s.%(funcName)s:%(lineno)s- %(message)r',
        },
        # RequestTimingMiddleware emits already-colored messages; keep the
        # formatter minimal so we don't escape-mangle the ANSI sequences.
        'access': {
            'format': '%(asctime)s %(levelname)-8s %(message)s',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        # Django's default request handler emits a duplicate WARNING
        # ("Unauthorized: /path") on top of our own access log for
        # every 4xx. Silence it by raising the threshold to ERROR so
        # 4xx/5xx don't double-log and we keep our structured access
        # line as the single source of truth for request outcomes.
        # 5xx crashes still surface here because Django logs the full
        # traceback at ERROR level before our middleware runs its log.
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'notechondria.access': {
            'handlers': ['console_access'],
            'level': 'INFO',
            'propagate': False,
        },
        # Shaped auth/permission failure lines emitted by our DRF
        # exception handler. Goes to the standard `console` (verbose)
        # + `file` handlers so both operator streams pick it up.
        'notechondria.auth': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Note CRUD + sync structured events (create / update / delete /
        # attachment / version restore). All lines are §1.7-shaped
        # ("<consequence>: Backend.Notes.<area>/<process> \u2014 <cause>").
        'notechondria.notes': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    # all the logging will propagate to root. so use root to save your log
    'root': {
        'handlers': ['file', ],
        'level': 'DEBUG',
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_database_url = os.getenv('DATABASE_URL')
if _database_url:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(_database_url, conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRE_DB', 'postgres'),
            'USER': os.getenv('POSTGRE_USERNAME'),
            'PASSWORD': os.getenv('POSTGRE_PASSWORD'),
            'HOST': os.getenv('POSTGRE_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRE_PORT', '5432'),
        }
    }

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "creators.authentication.ApiKeyAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    # Our handler emits one AGENTS.md §1.7-shaped log line per
    # auth/permission failure, then delegates to DRF's default
    # handler for the actual HTTP response.
    "EXCEPTION_HANDLER": "notechondria.drf_exception_handler.handle",
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  
        "OPTIONS": {
            "min_length": 9,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Automatic primary key for those who don't set, and the default feature name is id
# https://docs.djangoproject.com/en/3.2/topics/db/models/#automatic-primary-key-fields
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# you should not use django to process your static files, the static url should be set to other file providing url
STATIC_URL = '/static/'

# static file in the project folder (global)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# keep Django and nginx pointed at the same static directory regardless of DEBUG
STATIC_ROOT = env_path('DJANGO_PRODUCTION_STATIC_ROOT', BASE_DIR / 'productionfiles')

# Image files (jpg, jpeg)
# reference: https://djangocentral.com/uploading-images-with-django/

# Base url to serve media files
MEDIA_URL = '/media/'

# keep Django and nginx pointed at the same media directory regardless of DEBUG
MEDIA_ROOT = env_path('DJANGO_PRODUCTION_MEDIA_ROOT', BASE_DIR / 'mediafiles')

# ---------------------------------------------------------------------------
# Cloudflare R2 storage (S3-compatible)
# ---------------------------------------------------------------------------
# When CLOUDFLARE_R2_BUCKET_NAME is set, both static and media files are
# served from R2.  This is required on Render (no persistent disk) and
# optional for Docker Compose (persistent volumes + nginx work fine).
_R2_BUCKET = os.getenv('CLOUDFLARE_R2_BUCKET_NAME', '').strip()
_R2_ACCOUNT_ID = os.getenv('CLOUDFLARE_R2_ACCOUNT_ID', '').strip()
_R2_ACCESS_KEY = os.getenv('CLOUDFLARE_R2_ACCESS_KEY_ID', '').strip()
_R2_SECRET_KEY = os.getenv('CLOUDFLARE_R2_SECRET_ACCESS_KEY', '').strip()
_R2_CUSTOM_DOMAIN = os.getenv('CLOUDFLARE_R2_CUSTOM_DOMAIN', '').strip()

if _R2_BUCKET:
    # Validate that all required credentials are present.
    _missing = [
        name for name, val in [
            ('CLOUDFLARE_R2_ACCOUNT_ID', _R2_ACCOUNT_ID),
            ('CLOUDFLARE_R2_ACCESS_KEY_ID', _R2_ACCESS_KEY),
            ('CLOUDFLARE_R2_SECRET_ACCESS_KEY', _R2_SECRET_KEY),
        ] if not val
    ]
    if _missing:
        raise RuntimeError(
            f"Cloudflare R2 bucket is configured (CLOUDFLARE_R2_BUCKET_NAME={_R2_BUCKET!r}) "
            f"but the following required env vars are missing: {', '.join(_missing)}"
        )

    # S3-compatible endpoint for Cloudflare R2.
    _R2_ENDPOINT = f'https://{_R2_ACCOUNT_ID}.r2.cloudflarestorage.com'

    # Public URL base.  When a Cloudflare R2 custom domain (or r2.dev
    # subdomain) is set, use it.  Otherwise fall back to the S3 endpoint.
    _R2_URL_BASE = f'https://{_R2_CUSTOM_DOMAIN}' if _R2_CUSTOM_DOMAIN else _R2_ENDPOINT

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'bucket_name': _R2_BUCKET,
                'endpoint_url': _R2_ENDPOINT,
                'access_key': _R2_ACCESS_KEY,
                'secret_key': _R2_SECRET_KEY,
                'custom_domain': _R2_CUSTOM_DOMAIN or None,
                'default_acl': None,
                'location': 'media',
                'file_overwrite': False,
                'signature_version': 's3v4',
                'region_name': 'auto',
            },
        },
        'staticfiles': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'bucket_name': _R2_BUCKET,
                'endpoint_url': _R2_ENDPOINT,
                'access_key': _R2_ACCESS_KEY,
                'secret_key': _R2_SECRET_KEY,
                'custom_domain': _R2_CUSTOM_DOMAIN or None,
                'default_acl': None,
                'location': 'static',
                'file_overwrite': True,
                'signature_version': 's3v4',
                'region_name': 'auto',
            },
        },
    }
    STATIC_URL = f'{_R2_URL_BASE}/static/'
    MEDIA_URL = f'{_R2_URL_BASE}/media/'

# Maximum upload size: 20 MB (for note attachments).
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

# Offline development tag
OFFLINE = False

# login url

LOGIN_URL="/creators/login"

# LOGIN_REDIRECT_URL="/creators/profile"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("SMTP_HOST", "")
EMAIL_PORT = int(os.getenv("SMTP_PORT", "587"))
EMAIL_HOST_USER = os.getenv("SMTP_USERNAME", "")
EMAIL_HOST_PASSWORD = os.getenv("SMTP_PASSWORD", "")
EMAIL_USE_TLS = env_bool("SMTP_USE_TLS", True)
EMAIL_USE_SSL = env_bool("SMTP_USE_SSL", False)
DEFAULT_FROM_EMAIL = os.getenv("SMTP_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@notechondria.local")
EMAIL_VERIFICATION_TTL_HOURS = int(os.getenv("SMTP_EMAIL_VERIFICATION_TTL_HOURS", "24"))
FRONTEND_VERIFY_URL = os.getenv("FRONTEND_VERIFY_URL", "")

# OAuth / Social Login
GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", "")
GOOGLE_AUTHORIZED_REDIRECT_URI = os.getenv("GOOGLE_AUTHORIZED_REDIRECT_URI", "")
GITHUB_APP_CLIENT_ID = os.getenv("GITHUB_APP_CLIENT_ID", "")
GITHUB_APP_CLIENT_SECRET = os.getenv("GITHUB_APP_CLIENT_SECRET", "")
GITHUB_AUTHORIZED_REDIRECT_URI = os.getenv("GITHUB_AUTHORIZED_REDIRECT_URI", "")
